# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '문제 설명 관리',
                'verbose_name_plural': '문제 설명 관리',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '중1초급'), (2, '중1중급'), (3, '중1상급'), (4, '중2초급'), (5, '중2중급'), (6, '중2상급'), (7, '중3초급'), (8, '중3중급'), (9, '중3상급'), (10, '고1초급'), (12, '고1중급'), (13, '고1상급'), (14, '고2초급'), (15, '고2중급'), (16, '고2상급'), (17, '고3초급'), (18, '고3중급'), (19, '고3상급'), (20, '수능'), (0, '모름')], default=0, verbose_name='문제 수준')),
                ('question_type', models.IntegerField(choices=[(1, '문법'), (2, '어휘'), (3, '독해'), (4, '종합'), (0, '기타')], default=0, verbose_name='문제 유형')),
                ('title', models.CharField(max_length=100, verbose_name='문제')),
                ('text', models.CharField(max_length=30000, verbose_name='지문')),
                ('limit_time', models.PositiveSmallIntegerField(default=100, verbose_name='제한시간(초)')),
                ('correct', models.CharField(max_length=512, verbose_name='정답 답안')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '문제 은행',
                'verbose_name_plural': '문제 은행',
            },
        ),
        migrations.CreateModel(
            name='QuestionExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_sentence_1', models.CharField(blank=True, max_length=100, verbose_name='보기1')),
                ('ex_sentence_2', models.CharField(blank=True, max_length=100, verbose_name='보기2')),
                ('ex_sentence_3', models.CharField(blank=True, max_length=100, verbose_name='보기3')),
                ('ex_sentence_4', models.CharField(blank=True, max_length=100, verbose_name='보기4')),
                ('ex_sentence_5', models.CharField(blank=True, max_length=100, verbose_name='보기5')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '중1초급'), (2, '중1중급'), (3, '중1상급'), (4, '중2초급'), (5, '중2중급'), (6, '중2상급'), (7, '중3초급'), (8, '중3중급'), (9, '중3상급'), (10, '고1초급'), (12, '고1중급'), (13, '고1상급'), (14, '고2초급'), (15, '고2중급'), (16, '고2상급'), (17, '고3초급'), (18, '고3중급'), (19, '고3상급'), (20, '수능'), (0, '모름')], default=0, verbose_name='테스트 수준')),
                ('title', models.CharField(max_length=50, verbose_name='테스트 제목')),
                ('starting_date', models.DateTimeField(blank=True, null=True, verbose_name='테스트 시작 날짜')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='테스트 마감 날짜')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(to='quiz.Question', verbose_name='문제')),
                ('students', models.ManyToManyField(to='accounts.Student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '퀴즈 관리',
                'verbose_name_plural': '퀴즈 관리',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default='', max_length=512, verbose_name='학생 답')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답?')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
            options={
                'verbose_name': '학생 답안지',
                'verbose_name_plural': '학생 답안지',
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='점수')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
            options={
                'verbose_name': '성적',
                'verbose_name_plural': '성적',
            },
        ),
        migrations.AddField(
            model_name='explanations',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
